### ISSUE TITLE
Missing obs_mode="pointcloud+robot_seg" in env/wrapper.py

### ISSUE THREAD

**Issue by HeegerGao** [haosulab/ManiSkill2-Learn#12]
Hi, I find that in Maniskill2, the environment supports `obs_mode=pointcloud+robot_seg`, which will add robot segmentation in the returned observation dict. However, in ManiSkill2-Learn, in `env/wrapper.py`, there seems no branch for `obs_mode=pointcloud+robot_seg`, and if I set `obs_mode=pointcloud+robot_seg`, I will go to the [`else`](https://github.com/haosulab/ManiSkill2-Learn/blob/main/maniskill2_learn/env/wrappers.py#L649) branch.

Is that true? Or is there any other good way to get robot segmentation in pointcloud observation? Thanks!

**Comment by xuanlinli17** [comment]
Hi,

Yes it's true. For simplicity we only implemented `obs_mode = state / rgbd / pointcloud`. If you'd like to support "pointcloud+robot_seg", you can modify `env/wrapper.py` and customize it.

**Comment by HeegerGao** [comment]
Thanks for your quick reply! OK, I will customize it. I just think maybe ManiSkill2-Learn should keep the same APIs as ManiSkill2.
