### ISSUE TITLE
Assertion message misleading in `maniskill2_learn/env/rollout.py`

### ISSUE THREAD

**Issue by chenjy2003** [haosulab/ManiSkill2-Learn#25]
There is an assertion in `maniskill2_learn/env/rollout.py: 123`. The order in the assertion itself and the message is inconsistent, which misleads me a bit.

``` python
assert num % self.num_envs == 0, f"{self.num_envs} % {num} != 0, some processes are idle, you are wasting memory!"
```

**Comment by xuanlinli17** [comment]
Thanks for pointing this out!
