### ISSUE TITLE
How to remove the green words in saved videos

### ISSUE THREAD

**Issue by xtli12** [haosulab/ManiSkill2-Learn#28]
Hi, what commond should I use to remove the green words in saved videos?
![image](https://github.com/haosulab/ManiSkill2-Learn/assets/86363634/9de12c1b-9c84-4f0a-b8d8-18723fcecfb5)

**Comment by xuanlinli17** [comment]
Comment this line out:
https://github.com/haosulab/ManiSkill2-Learn/blob/9a2fd11d900ec965eecdf9ec38c33cbc5b3bf8f5/maniskill2_learn/env/env_utils.py#L164

**Comment by xtli12** [comment]
Thanks a lot, happy new year!
