### ISSUE TITLE
Reproducing PPO-PickCubeV0-rgbd with Error

### ISSUE THREAD

**Issue by pumfish** [haosulab/ManiSkill2-Learn#33]
Hello, I'm trying to reproduce the dapg + PickCubev0 + rgbd experiment follow the examples.
My ManiSkill2-Learn branch is **main**, and ManiSkill version is **v0.5.0**
I firstly generate the data using the scrips ```ManiSkill2-Learn/scripts/example_demo_conversion/pick_place_single_object_env.sh``` with no change, then I run the follow scripts:
``` 
python maniskill2_learn/apis/run_rl.py configs/mfrl/dapg/maniskill2_rgbd.py \
             --work-dir ${LOG_DIR} --dev --gpu-ids ${GPU_ID}  \
             --cfg-options "env_cfg.env_name=PickCube-v0" "env_cfg.obs_mode=rgbd" \
             "env_cfg.control_mode=pd_ee_delta_pose" \
             "rollout_cfg.num_procs=12" "env_cfg.reward_mode=dense" \
             "agent_cfg.demo_replay_cfg.buffer_filenames=../ManiSkill/v0/demos/rigid_body/PickCube-v0/trajectory.none.pd_ee_delta_pose_rgbd.h5" \
             "eval_cfg.num=100" "eval_cfg.save_traj=True" "eval_cfg.save_video=True" \
             "train_cfg.total_steps=25000000" "train_cfg.n_checkpoint=1000000" "train_cfg.n_eval=1000000"
```
but I got:
```assert key in self.demo_replay.memory, f"DAPG needs {key} in your demo!"```
I found the ```self.demo_replay.memory``` is empty, how can I fix it?

**Comment by xuanlinli17** [comment]
Are the files non-empty after running https://github.com/haosulab/ManiSkill2-Learn/blob/main/scripts/example_demo_conversion/pick_place_single_object_envs.sh ?

**Comment by pumfish** [comment]
I realized that we had the wrong path. Training is now proceeding correctly, and we are currently awaiting the results. Thank you very much for your response!
