### ISSUE TITLE
The meaning of "terminated" and "truncated"

### ISSUE THREAD

**Issue by pumfish** [haosulab/ManiSkill2-Learn#34]
Hello, I'm trying to add new simulation environment experiments in ```ManiSkill2-Learn```. 
While modifying the code, I noticed the following function in ```vec_env.py```.
```python
    # Special functions
    def step_dict(self, actions, idx=None, restart=True):
        idx, slice_idx = self._process_idx(idx)
        obs = self.recent_obs.slice(slice_idx).copy(wrapper=False)
        next_obs, reward, terminated, truncated, info = self.step(actions, idx=idx)
        term_or_trunc = np.logical_or(terminated, truncated)
        if np.any(term_or_trunc) and restart:
            self.reset(idx=np.where(term_or_trunc[..., 0])[0])
            
        return dict(
            obs=obs,
            next_obs=next_obs,
            actions=GDict(actions).f64_to_f32(wrapper=False),
            rewards=reward,
            dones=terminated,
            episode_dones=term_or_trunc,
            infos=info,
            worker_indices=idx,
        )
```
I checked the ```step``` function in ManiSkill2 and found that ```truncated``` is set to ```False```. Doesn't that mean ```dones``` will always equal ```episode_dones```? 
Also, when a task is completed successfully and when a task reaches the maximum number of steps, what value should ```terminated``` return?

**Comment by xuanlinli17** [comment]
`dones` doesn't equal to `episode_dones`. See https://github.com/haosulab/ManiSkill2-Learn/blob/e9860aff595da3ad34829d62c923be0b50001427/tools/convert_state.py#L123 . `episode_dones` is merely an episode separator, while `dones` is success indicator. `dones` corresponds to `terminated` while `episode_dones` corresponds to `truncated`.

**Comment by pumfish** [comment]
Thank you for your prompt response! Your explanation clearly addressed my confusion. I have adjusted my code, and it is now running smoothly. I really appreciate your help!
